headingLevels:
  - 2
  - 3
  - 4
  - 5
js: "return {\r\n  list: {\r\n    properties: {\r\n      style: false,\r\n    },\r\n  },\r\n}"
name: Legal
toolbar:
  - heading
  - bulletedList
  - numberedList
  - '|'
  - bold
  - italic
  - link
  - '|'
  - removeFormat
  - selectAll
  - findAndReplace
  - undo
  - redo
  - sourceEditing
