fieldLayouts:
  f0242c77-2436-442e-b705-e289bd9c48f2:
    tabs:
      -
        elements:
          -
            fieldUid: 56586313-03c2-4ded-b0c3-d22dee297e67 # Organization
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4f2acaa1-189a-4e2d-ad0c-f313c4b00118 # Socials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Organization
        sortOrder: 1
      -
        elements:
          -
            fieldUid: e0fec26e-937b-4d32-b433-211242db4d9e # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 78376c37-546a-4c5a-b132-d9d8c8acf806 # Twitter Handle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: configuration
name: Configuration
sortOrder: 1
