dateModified: 1748967069
elementSources:
  craft\elements\Asset:
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:7c06f121-409c-4ebe-a6ce-aa78ea61ce4d' # Assets
      tableAttributes:
        - filename
        - size
        - alt
        - link
        - dateUpdated
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: false
      key: 'volume:3c0c2fcb-c361-472f-80d1-6bb4e36bcab6' # Stream
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
      type: native
    -
      defaultSort:
        - dateCreated
        - desc
      disabled: true
      key: temp
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
      type: native
    -
      key: 'volume:7b21edba-fb22-4729-8c3b-ada8d7692fb7'
      type: native
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: true
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
        - 'fieldInstance:f0b93103-f347-46cf-a35a-1d615e451ac7'
      type: native
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 427bf5cd-a59b-490b-b909-59f7aeeef7a6
            values:
              - 9477a487-01b6-4a09-bb9b-4e4fdc45d8c6 # Media specs
              - 3bf78167-9a80-4012-b67c-faf5e0984c25 # Scripts
              - 6a42e96b-9b9a-42b8-8dab-2e39ffbeb7cc # Site configuration
              - ff4e6d75-2bed-40aa-8718-1e77a25a37d7 # Site footer
              - 800d763b-bbca-482a-9345-81b70bf730b2 # Site header
              - 55239922-65f1-4558-96b1-71848e51a9bc # Cookie Banner
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:1363d8c9-0624-4681-802c-6d73aeb2c5bc'
      label: Globals
      tableAttributes: '-'
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 38c6dc4c-a415-4e43-8298-6c8aa55610bb
            values:
              - 6c86c074-7558-42ed-9fbc-8c4fbc736b95 # Blog
              - 0982d07a-c328-4033-8695-305319d78835 # Careers
              - 4a4ac845-5be1-4d2d-bb12-617c872d2ee5 # Contact
              - da1b5819-b168-4dd9-aa35-505a833ee367 # Homepage
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:eef88424-12ea-4adc-a32f-6d6df4466116'
      label: Singles
      tableAttributes: '-'
      type: custom
    -
      defaultSort:
        - title
        - asc
      disabled: true
      key: singles
      tableAttributes:
        - slug
        - link
        - revisionCreator
        - dateUpdated
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:ec8f8144-4229-4395-adcd-105b11962c8a' # Pages
      tableAttributes:
        - slug
        - 'field:7c46388e-1ad1-466a-a30f-c138c9477b0f' # Modules
        - link
        - dateUpdated
        - revisionCreator
      type: native
    -
      heading: Content
      type: heading
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: 'section:c2b278b1-d1f1-4dc9-91f2-716fddb29525' # Articles
      tableAttributes:
        - slug
        - link
        - dateUpdated
        - revisionCreator
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:f23e6a71-9e92-4184-bdd9-8ff3775fb2ec' # Jobs
      tableAttributes:
        - slug
        - link
        - dateUpdated
        - revisionCreator
      type: native
    -
      heading: Categories
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:c26c7142-c8a9-4cac-b0ea-c84428d04864' # Blog topics
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      heading: Components
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:414b45c8-d274-4c58-b6e8-f0ce31130d34' #  Modules
      tableAttributes:
        - postDate
        - expiryDate
        - link
        - type
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:46ed0eb4-8c01-447c-9087-62ca99521b71' # Partners
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
email:
  fromEmail: $EMAIL_FROM
  fromName: $SITE_NAME
  replyToEmail: null
  template: ''
  transportSettings:
    apiKey: $SENDGRID_API
    categories: ''
  transportType: putyourlightson\sendgrid\mail\SendgridAdapter
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: $ASSETS_FILE_SYSTEM_PATH
    type: craft\fs\Local
    url: $UPLOADS_URL
  stream:
    hasUrls: false
    name: Stream
    settings:
      path: $STREAM_FILE_SYSTEM_PATH
    type: craft\fs\Local
    url: $STREAM_URL
meta:
  __names__:
    0d817cce-530a-4dbe-bc87-c42dee45463a: 'Tiroir // Drawer' # Tiroir // Drawer
    0f0e5f88-9336-4032-bfa2-11083f5fa132: 'CMS Identifier' # CMS Identifier
    1b87bba6-669b-4114-b597-210e967e2891: Legal # Legal
    2f4cc73e-1fcb-41c0-a892-a938426d92cf: Images # Images
    3b201410-7c1b-4123-aa95-e7e742a06113: Scripts # Scripts
    3bf78167-9a80-4012-b67c-faf5e0984c25: Scripts # Scripts
    3c0c2fcb-c361-472f-80d1-6bb4e36bcab6: Stream # Stream
    3ce9ecc2-8c9b-4d1f-962c-eca70eee7033: Title # Title
    3d598329-9100-4395-99d6-00ba71ab632c: Articles # Articles
    3f07a8e2-b80b-4fe0-aca4-9c505738579d: Narrative # Narrative
    4a4ac845-5be1-4d2d-bb12-617c872d2ee5: Contact # Contact
    4c508769-fc04-4e88-9cfd-85313caaf2b4: Script # Script
    4dabd377-5b99-4269-90ab-1129bab3dea0: 'Plain text - Multiline' # Plain text - Multiline
    5b29e282-f0ce-4929-834a-4953ec2b7dd3: 'Cookie Banner' # Cookie Banner
    6a42e96b-9b9a-42b8-8dab-2e39ffbeb7cc: 'Site configuration' # Site configuration
    6abc4a11-ddf3-44c7-b156-42847f10eae2: 'Enable cookie banner' # Enable cookie banner
    6c86c074-7558-42ed-9fbc-8c4fbc736b95: Blog # Blog
    7c06f121-409c-4ebe-a6ce-aa78ea61ce4d: Assets # Assets
    7c46388e-1ad1-466a-a30f-c138c9477b0f: Modules # Modules
    7d6d33a6-5d21-417b-a4e7-def3b8a03c8f: Topics # Topics
    7f423144-c38b-4ed4-916e-132f44e9e1d6: 'Blog topic' # Blog topic
    8a2d5af3-151b-4ea4-9882-c0579fbe91f9: 'Citation avec source // Quote with source' # Citation avec source // Quote with source
    9de68a16-72b4-4696-afea-63d53c5a01bc: Partners # Partners
    9e18815d-4be1-43b2-9287-19eef168429b: Invert # Invert
    9ec6fdb3-b8d0-4641-96b9-16c9875584fa: Text # Text
    10a5c368-5d0b-47a4-9978-105511f5e998: SEO # SEO
    16e1ca14-9781-44a1-b17f-7489cef3700a: 'Boutons // Buttons' # Boutons // Buttons
    19f03eed-fb4d-447e-966d-258f5e5add92: ' Legal' #  Legal
    20d16447-9c20-40a5-a82e-1ff60c050e89: 'Public Schema' # Public Schema
    24fcc82a-e774-4756-8f1e-62edb2119633: 'Rich text - Inline' # Rich text - Inline
    39fc315f-bb9e-46f7-877a-dcdd711c1aed: 'Media spec' # Media spec
    46e9d2cf-9ffa-4d70-b132-f32d2c4c4c58: Embed # Embed
    46ed0eb4-8c01-447c-9087-62ca99521b71: Partners # Partners
    59d5a6cf-12d1-4545-97b4-16e72fe93b7f: Link # Link
    63a8cb64-067e-4061-adfa-2d615a0d9e63: 'CTA ' # CTA 
    80faeb96-cf17-464b-aae2-cbf334c38969: 'Rich text - Simple' # Rich text - Simple
    89a0d307-caf6-4065-836e-f59cea4d6bf7: Simple # Simple
    095f6b18-db1d-40dc-9362-d2a489860e4b: Accordion # Accordion
    99a344a6-d5b9-4dfb-8ab7-9d6909dd6644: 'Share image' # Share image
    148fb449-e797-4b40-a8f8-d45d858683dd: 'Texte // Text' # Texte // Text
    247fed59-90e6-4b37-ac0c-a42cfa306a81: 'Média // Media' # Média // Media
    414b45c8-d274-4c58-b6e8-f0ce31130d34: ' Modules' #  Modules
    492f0e2c-a4d9-43f1-bbe3-088788243930: Careers # Careers
    615c8eda-5043-4fdd-a90c-3c77212764e6: 'Plain text' # Plain text
    0630a2e9-2fbf-476c-b8e4-8586a57d1366: Article # Article
    663c4e72-de2b-4558-9123-f2db43c01252: Article # Article
    800d763b-bbca-482a-9345-81b70bf730b2: 'Site header' # Site header
    923cdc41-2e7b-4d9a-898b-4bf76d14bcc7: 'Read time' # Read time
    0982d07a-c328-4033-8695-305319d78835: Careers # Careers
    3070e537-2129-43f0-addf-fbae4049f8e1: Media # Media
    3221aacd-9b06-4daa-a21c-d632a438983d: 'Prose drawers' # Prose drawers
    4093afd2-c348-4b4b-9137-0e07daa80e57: Text-Media # Text-Media
    8534cb8d-ec47-4d88-a55d-3e22d08c402b: Logo # Logo
    9477a487-01b6-4a09-bb9b-4e4fdc45d8c6: 'Media specs' # Media specs
    22947fe1-4c0e-437b-9997-de04319d78e3: 'Rich text - Full' # Rich text - Full
    66232f4e-2ac7-45d0-9cf4-9867b9b96ada: 'Tiroirs // Drawers' # Tiroirs // Drawers
    0145468f-d01a-4e00-bdf3-d734c3e52a72: Inline # Inline
    374406b8-233f-4e1b-ae1e-f779112eaca6: Article # Article
    2556508a-1412-450e-8cad-0369ef9cced4: Url # Url
    55239922-65f1-4558-96b1-71848e51a9bc: 'Cookie Banner' # Cookie Banner
    85050609-12b8-4783-b9c6-5f753f3fe36b: Full # Full
    a0a65bff-fadd-4bb4-ae89-c3f15c01bbbc: Carousel # Carousel
    a03206c2-0f1f-4ac9-affe-b6a82de9bf75: 'Site configuration' # Site configuration
    a2444205-7b4b-4062-82d8-74833e3f5f80: Job # Job
    a4075417-c1ab-4ea9-86bb-9848b83afec3: 'Video Stream (pour les Asset Volumes seulement)' # Video Stream (pour les Asset Volumes seulement)
    af0b5372-3e37-4dbd-afcc-c9aa66cea831: "Appel à l'action // Call to Action" # Appel à l'action // Call to Action
    af77db16-7383-4e3b-ae49-71b93d94b959: FR # FR
    b09fcabc-7f1c-40b8-b8d3-f085835a0c24: Homepage # Homepage
    b5f2bd1d-dd60-4cf4-8fb8-cf314d30a192: 'Vidéo encastrée (Embed) // Embed Video' # Vidéo encastrée (Embed) // Embed Video
    b7d20b42-135e-4d76-85cd-1e890b36c30a: Text # Text
    b40c3a12-3bed-46f5-97c6-941c7a839154: 'Vidéo Embed // Embed Video' # Vidéo Embed // Embed Video
    b56dc3db-a457-4448-9fec-dd6a5a543696: Image # Image
    b851c78b-d4f2-420f-8018-3d24a4cfb7d2: 'Embed URL' # Embed URL
    bdc09e8f-fc0f-420e-b3f0-af6980757e6b: 'Site header' # Site header
    c2b278b1-d1f1-4dc9-91f2-716fddb29525: Articles # Articles
    c5bc89a7-34ff-4d1e-b2ed-9be8d9e044da: EN # EN
    c26c7142-c8a9-4cac-b0ea-c84428d04864: 'Blog topics' # Blog topics
    caa63442-86cb-4489-baad-9aba2dc43dba: 'No index' # No index
    cc5591b6-0516-4dfb-8b70-671168f3b268: Partner # Partner
    d9f3be47-624e-49ae-90d4-79880f18013e: Contact # Contact
    d54d25fa-9fc6-4fb2-96c7-17d51a9e91e9: 'Média // Media' # Média // Media
    da1b5819-b168-4dd9-aa35-505a833ee367: Homepage # Homepage
    dbc05352-c8d9-4615-a1c6-79954bf4033b: $SITE_NAME # $SITE_NAME
    dc92bc6c-36c7-4c5d-be20-91a74863ec70: Blog # Blog
    e0fec26e-937b-4d32-b433-211242db4d9e: SEO # SEO
    e4b3fe13-7dcf-4ebe-8edd-570b3fa7b618: Drawers # Drawers
    e8a9774e-14c6-4ae6-b673-a9740e5af59b: 'Plain text - Non-translatable' # Plain text - Non-translatable
    e20da329-fdd5-4405-92a6-3b6ea49914d1: Download # Download
    e30d53e2-8287-4791-9efa-184c3024366c: 'Emphase // Callout' # Emphase // Callout
    e60013a8-ce72-424b-9582-971b0ca73b09: Partners # Partners
    eb06fbb5-a0f2-44b3-88e4-f1355300f911: 'Rich Text - Article' # Rich Text - Article
    ec8f8144-4229-4395-adcd-105b11962c8a: Pages # Pages
    f8d9ad5c-7504-4ce3-a645-814f7094c056: 'Site footer' # Site footer
    f20d3272-0ab0-4656-aa6d-e27e58f20a40: Drawer # Drawer
    f23e6a71-9e92-4184-bdd9-8ff3775fb2ec: Jobs # Jobs
    f24c97e8-b8f5-4799-bb8f-c062c6196c51: 'Share description' # Share description
    f2599fa6-87fd-4abf-ae90-7bdafd0e3f31: Links # Links
    ff4e6d75-2bed-40aa-8718-1e77a25a37d7: 'Site footer' # Site footer
plugins:
  admin-panel-controllers:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  agency-auth:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  blur-hash:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cloudflare-stream:
    edition: standard
    enabled: true
    licenseKey: 
    schemaVersion: 1.4.0
    settings:
      accountId: $CF_STREAM_ACCOUNT_ID
      apiToken: $CF_STREAM_API_TOKEN
      autoUpload: '1'
      useFormUpload: '1'
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.3
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  fonts-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  hyper:
    edition: standard
    enabled: true
    licenseKey: 
    schemaVersion: 1.0.0
  routes-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  sendgrid:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vizy:
    edition: standard
    enabled: true
    licenseKey: 
    schemaVersion: 0.9.0
system:
  edition: pro
  live: true
  name: $SITE_NAME
  retryDuration: 60
  schemaVersion: 5.7.0.3
  timeZone: America/Toronto
