name: Runs shellcheck

on:
  push:
    paths:
      - '*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        severity: error
